RegFifo = 0x00 # FIFO read/write access
RegOpMode = 0x01 # Operating mode &  LoRa TM / FSK selection
RegBitrateMsb = 0x02 # Bit Rate setting, Most Significant Bits
RegBitrateLsb = 0x03 # Bit Rate setting, Least Significant Bits
RegFdevMsb = 0x04 # Frequency Deviation setting, Most Significant Bits
RegFdevLsb = 0x05 # Frequency Deviation setting, Least Significant Bits
RegFrfMsb = 0x06 # RF Carrier Frequency, Most Significant Bits
RegFrfMid = 0x07 # RF Carrier Frequency, Intermediate Bits
RegFrfLsb = 0x08 # RF Carrier Frequency, Least Significant Bits
RegPaConfig = 0x09 # PA selection and Output Power control
RegPaRamp = 0x0A # Control of PA ramp time, low phase noise PLL
RegOcp = 0x0B # Over Current Protection control
RegLna = 0x0C # LNA settings
RegRxConfig = 0x0D # AFC, AGC, ctrl
RegRssiConfig = 0x0E # RSSI
RegRssiCollision = 0x0F # RSSI Collision detector
RegRssiThresh = 0x10 # RSSI Threshold control
RegRssiValue = 0x11 # RSSI value in dBm
RegRxBw = 0x12 # Channel Filter BW Control
RegAfcBw = 0x13 # AFC Channel Filter BW 
RegOokPeak = 0x14 # OOK demodulator
RegOokFix = 0x15 # Threshold of the OOK demod
RegOokAvg = 0x16 # Average of the OOK demod
RegAfcFei = 0x1A # AFC and FEI control
RegAfcMsb = 0x1B # Frequency correction value of the AFC
RegAfcLsb = 0x1C # Frequency correction value of the AFC
RegFeiMsb = 0x1D # Value of the calculated frequency error
RegFeiLsb = 0x1E # Value of the calculated frequency error
RegPreambleDetect = 0x1F # Settings of the Preamble Detector
RegRxTimeout1 = 0x20 # Timeout Rx request and RSSI
RegRxTimeout2 = 0x21 # Timeout RSSI and PayloadReady
RegRxTimeout3 = 0x22 # Timeout RSSI and SyncAddress
RegRxDelay = 0x23 # Delay between Rx cycles
RegOsc = 0x24 # RC Oscillators Settings, CLKOUT frequency
RegPreambleMsb = 0x25 # Preamble length, MSB 
RegPreambleLsb = 0x26 # Preamble length, LSB
RegSyncConfig = 0x27 # Sync Word Recognition control
RegSyncValue1 = 0x28 # Sync Word byte 1
RegSyncValue2 = 0x29 # Sync Word byte 2
RegSyncValue3 = 0x2A # Sync Word byte 3
RegSyncValue4 = 0x2B # Sync Word byte 4
RegSyncValue5 = 0x2C # Sync Word byte 5
RegSyncValue6 = 0x2D # Sync Word byte 6
RegSyncValue7 = 0x2E # Sync Word byte 7
RegSyncValue8 = 0x2F # Sync Word byte 8
RegPacketConfig1 = 0x30 # Packet mode settings
RegPacketConfig2 = 0x31 # Packet mode settings
RegPayloadLength = 0x32 # Payload length setting
RegNodeAdrs = 0x33 # Node address
RegBroadcastAdrs = 0x34 # Broadcast address
RegFifoThresh = 0x35 # Fifo threshold, Tx start condition
RegSeqConfig1 = 0x36 # Top level Sequencer settings
RegSeqConfig2 = 0x37 # Top level Sequencer settings
RegTimerResol = 0x38 # Timer 1 and 2 resolution control
RegTimer1Coef = 0x39 # Timer 1 setting
RegTimer2Coef = 0x3A # Timer 2 setting
RegImageCal = 0x3B # Image calibration engine control
RegTemp = 0x3C # Temperature Sensor value
RegLowBat = 0x3D # Low Battery Indicator Settings
RegIrqFlags1 = 0x3E # Status register: PLL Lock state, Timeout, RSSI
RegIrqFlags2 = 0x3F # Status register: FIFO handling flags, Low Battery 
RegDioMapping1 = 0x40 # Mapping of pins DIO0 to DIO3
RegDioMapping2 = 0x41 # Mapping of pins DIO4 and DIO5, ClkOut frequency
RegVersion = 0x42 # Semtech ID relating the silicon revision
RegPllHop = 0x44 # Control the fast frequency hopping mode
RegTcxo = 0x4B # TCXO or XTAL input setting
RegPaDac = 0x4D # Higher power settings of the PA
RegFormerTemp = 0x5B # Stored temperature during the former IQ Calibration
RegBitRateFrac = 0x5D # Fractional part in the Bit Rate division ratio
RegAgcRef = 0x61 # Adjustment of the AGC thresholds
RegAgcThresh1 = 0x62 # Adjustment of the AGC thresholds
RegAgcThresh2 = 0x63 # Adjustment of the AGC thresholds
RegAgcThresh3 = 0x64 # Adjustment of the AGC thresholds
RegPll = 0x70 # Control of the PLL bandwidth
